In [11]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import pydotplus 
import graphviz  
from sklearn.model_selection import train_test_split
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn import tree
from sklearn.metrics import ConfusionMatrixDisplay



In [12]:
## Read in data
## Link to the dataset: https://drive.google.com/file/d/1lQ85Ftir5F8gNpI833hC52_8GgcMiGJp/view?usp=sharing

#!! YOU will need to change this path to match the path on YOUR computer !!
filename = "C:/Users/ryhen/OneDrive - UCB-O365/Machine Learning/Project/Part 3/Decision_Trees/HeartRisk_JustNums_4D_Labeled.csv"
#Read in the data
HeartRiskDF = pd.read_csv(filename)
print(HeartRiskDF)



     Label  Cholesterol  Weight  Height  BMI
0     Risk          251     267      70   30
1   Medium          105     103      62   19
2   NoRisk          156     193      72   20
3   NoRisk          109     100      63   20
4   Medium          198     210      70   25
5     Risk          189     189      64   26
6     Risk          121     105      65   21
7   NoRisk          134     125      60   20
8     Risk          250     156      69   29
9   NoRisk          118     190      71   19
10  Medium          290     300      62   31
11  NoRisk          156     119      69   24
12  NoRisk          145     112      68   23
13  Medium          178     177      68   27
14    Risk          175     145      63   26


In [13]:
HeartRiskDF_Train, HeartRiskDF_Test=train_test_split(HeartRiskDF,test_size=.30)
print("The Training Data is\n", HeartRiskDF_Train)
print("The Testing Data is\n", HeartRiskDF_Test)

The Training Data is
      Label  Cholesterol  Weight  Height  BMI
1   Medium          105     103      62   19
0     Risk          251     267      70   30
4   Medium          198     210      70   25
13  Medium          178     177      68   27
6     Risk          121     105      65   21
10  Medium          290     300      62   31
5     Risk          189     189      64   26
2   NoRisk          156     193      72   20
3   NoRisk          109     100      63   20
9   NoRisk          118     190      71   19
The Testing Data is
      Label  Cholesterol  Weight  Height  BMI
11  NoRisk          156     119      69   24
7   NoRisk          134     125      60   20
8     Risk          250     156      69   29
12  NoRisk          145     112      68   23
14    Risk          175     145      63   26


In [14]:
## Now remove the labels from the data - but keep and name the labels
TrainLabel = HeartRiskDF_Train["Label"]
print(TrainLabel)
## Remove the label from the dataset itself
HeartRiskDF_Train = HeartRiskDF_Train.drop(["Label"], axis=1)
print(HeartRiskDF_Train)

TestLabel = HeartRiskDF_Test["Label"]
print(TestLabel)
## Remove the label from the dataset itself
HeartRiskDF_Test = HeartRiskDF_Test.drop(["Label"], axis=1)
print(HeartRiskDF_Test)



1     Medium
0       Risk
4     Medium
13    Medium
6       Risk
10    Medium
5       Risk
2     NoRisk
3     NoRisk
9     NoRisk
Name: Label, dtype: object
    Cholesterol  Weight  Height  BMI
1           105     103      62   19
0           251     267      70   30
4           198     210      70   25
13          178     177      68   27
6           121     105      65   21
10          290     300      62   31
5           189     189      64   26
2           156     193      72   20
3           109     100      63   20
9           118     190      71   19
11    NoRisk
7     NoRisk
8       Risk
12    NoRisk
14      Risk
Name: Label, dtype: object
    Cholesterol  Weight  Height  BMI
11          156     119      69   24
7           134     125      60   20
8           250     156      69   29
12          145     112      68   23
14          175     145      63   26


In [15]:
##Instantiate the decision tree using the defaults.
MyDT_Classifier = DecisionTreeClassifier()
## Use fit to create the decision tree model
MyDT_Classifier = MyDT_Classifier.fit(HeartRiskDF_Train, TrainLabel)

FeatureNames=HeartRiskDF_Train.columns.values ## get all the feature/variable names
print(FeatureNames)
ClassNames=MyDT_Classifier.classes_ ## Get the class names
print(ClassNames)




['Cholesterol' 'Weight' 'Height' 'BMI']
['Medium' 'NoRisk' 'Risk']


In [16]:
##Tree Plot Option 1
MyPlot=tree.plot_tree(MyDT_Classifier,
                   feature_names=FeatureNames,  
                   class_names=ClassNames,
                   filled=True)

## !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
## To see the tree, open this file on your computer :)
## !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
plt.savefig("MyTree1.jpg")
plt.close()

 



In [17]:
## Visualize the tree ##--------------------------------------

## !!!!!!!!!!!!!!!!!
## To run this next part, you will need to 
## conda install python-graphviz
## If you cannot get it to work - don't worry about that for now
## Comment out the following lines.


TREE_Vis = tree.export_graphviz(MyDT_Classifier, 
                    out_file=None, 
                    feature_names=HeartRiskDF_Train.columns,  
                    class_names=ClassNames,  
                    filled=True, rounded=True,  
                    special_characters=True)  

graph = graphviz.Source(TREE_Vis)  
#Export to pdf
DT_graph = pydotplus.graph_from_dot_data(TREE_Vis)
## !!!!  Search for My_DT_tree.pdf on your computer and open it. 
## It will contain your tree ;)
DT_graph.write_pdf("My_DT_tree.pdf")
plt.close()



InvocationException: GraphViz's executables not found

In [18]:
## Use the Tree to make predictions
Prediction=MyDT_Classifier.predict(HeartRiskDF_Test)
print(Prediction)

Actual_Labels=TestLabel
print(Actual_Labels)
Predicted_Labels=Prediction

##Create the Basic Confusion Matrix
My_Conf_Mat = confusion_matrix(Actual_Labels, Predicted_Labels)
print(My_Conf_Mat)

## Confusion Plot Option 1
##Create the fancy CM using Seaborn
sns.heatmap(My_Conf_Mat, annot=True,cmap='Blues',xticklabels=ClassNames, 
            yticklabels=ClassNames, cbar=False)
plt.title("Confusion Matrix For Heart Risk Data",fontsize=20)
plt.xlabel("Actual", fontsize=15)
plt.ylabel("Predicted", fontsize=15)
plt.savefig("seaborn_plot.jpg", dpi=300)
plt.close()

## Confusion Matrix Plot Option 2
CM_disp=ConfusionMatrixDisplay(My_Conf_Mat,ClassNames)
CM_disp.plot()
plt.savefig("CM.jpg")
plt.close()

['Risk' 'NoRisk' 'Risk' 'Risk' 'Medium']
11    NoRisk
7     NoRisk
8       Risk
12    NoRisk
14      Risk
Name: Label, dtype: object
[[0 0 0]
 [0 1 2]
 [1 0 1]]


TypeError: ConfusionMatrixDisplay.__init__() takes 2 positional arguments but 3 were given